name: Security

on:
  schedule:
    # Run security checks daily at 2 AM UTC
    - cron: "0 2 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node.pnpm

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Check for outdated dependencies
        run: pnpm outdated || true
